set(VCPKG_DEPS_DIR "${PROJECT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}")

if(EXISTS "${VCPKG_DEPS_DIR}/include/hermes")
    set(Hermes_FOUND ON)
    set(Hermes_INCLUDE_DIR "${VCPKG_DEPS_DIR}/include")
    set(Hermes_LIBRARY "${VCPKG_DEPS_DIR}/lib/libhermesvm${CMAKE_SHARED_LIBRARY_SUFFIX}")
else()
    set(Hermes_FOUND OFF)
    message("[Error] Hermes library not found. Did you forgot to run `vcrun install`?")
    message("[Error]   searched in: ${VCPKG_DEPS_DIR}")
endif()

if (Hermes_FOUND AND NOT TARGET Hermes::Hermes)
    add_library(Hermes::Hermes UNKNOWN IMPORTED)
    set_property(TARGET Hermes::Hermes PROPERTY IMPORTED_LOCATION ${Hermes_LIBRARY})
    target_include_directories(Hermes::Hermes INTERFACE "${Hermes_INCLUDE_DIR}")
    target_link_libraries(Hermes::Hermes INTERFACE "${Hermes_LIBRARY}")
#    target_link_libraries(Hermes INTERFACE "${VCPKG_DEPS_DIR}/lib/hermes/lib/libhermesvm.dylib")
#    target_link_directories(Hermes INTERFACE "${VCPKG_DEPS_DIR}/lib/hermes/")
#    target_link_directories(Hermes INTERFACE "${VCPKG_DEPS_DIR}/lib/hermes/lib")
#    target_link_directories(Hermes INTERFACE "${VCPKG_DEPS_DIR}/lib/jsi/")
endif()